name: Remove ready to merge label
on:
  pull_request:
    types:
      - closed

jobs:
  remove_label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "status: ready to merge"
